# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./renderer
# Target is an application:  renderer.e

TARGET = renderer.e 
DESTDIR = ../bin 
CONFIG += release \
          warn_on 
TEMPLATE = app 
SOURCES += main.cpp 
